name: Deploy Wiki to DO
on:
  push:
      branches:
        - master

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Check Out Repo
          uses: actions/checkout@v2
        - name: Install DigitalOcean Controller
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
        - name: Set up Docker Builder
          uses: docker/setup-buildx-action@v1
        - name: Authenticate with DigitalOcean Container Registry
          run: doctl registry login --expiry-seconds 180
        - name: Build and Push to DigitalOcean Container Registry
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            file: DockerfileDO
            tags: |
              registry.digitalocean.com/gawth/wiki:latest
              registry.digitalocean.com/gawth/wiki:sha-${{ github.sha  }} 

  deploy-wiki:
      needs: build
      runs-on: ubuntu-latest
      steps:
        # Droplets already have docker, doctl + auth, and curl installed
        - name: Deploy wiki to DigitalOcean Droplet
          uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.DO_WIKI_HOST }} 
            username: root
            key: ${{ secrets.DO_WIKI_KEY }} 
            port: 22
            script: |
              doctl registry login --expiry-seconds 180
              docker pull registry.digitalocean.com/gawth/wiki:latest

              docker stop wiki || true
              docker rm wiki || true

              echo "starting server instance..."
              docker run -d \
                --restart always \
                -p 0.0.0.0:8990:8990 \
                --name wiki \
                registry.digitalocean.com/gawth/wiki:latest

